// Code generated by gotool. DO NOT EDIT.
// If you find any bugs, please contact heshiyingx@126.com.
// Your help is greatly appreciated.

package code

import (
	"context"

	"fmt"
	"strings"
	"time"

	"github.com/heshiyingx/gotool/dbext/gormdb"
	"gorm.io/gorm"
)

var (
	cacheNutritionStoreIdPrefix     = "cache:nutritionStore:id:"
	cacheNutritionStoreUserIdPrefix = "cache:nutritionStore:userId:"
)

type (
	nutritionStoreModel interface {
		Insert(ctx context.Context, data *NutritionStore, delCacheKeys ...string) (int64, error)
		FindById(ctx context.Context, id int64) (*NutritionStore, error)
		UpdateById(ctx context.Context, id int64, updateObj *NutritionStore, delCacheKeys []string, fields ...string) (int64, error)
		DeleteById(ctx context.Context, id int64, delCacheKeys ...string) (int64, error)
		FindOneByUserId(ctx context.Context, userId int64) (*NutritionStore, error)
		DeleteOneByUserId(ctx context.Context, userId int64, delCacheKeys ...string) (int64, error)
		UpdateOneByUserId(ctx context.Context, userId int64, updateObj *NutritionStore, delCacheKeys []string, fields ...string) (int64, error)
	}

	defaultNutritionStoreModel struct {
		db *gormdb.CacheGormDB[NutritionStore, int64]
	}

	NutritionStore struct {
		Id        int64      `db:"id" gorm:"column:id" json:"id,omitempty"`
		UserId    int64      `db:"user_id" gorm:"column:user_id" json:"user_id,omitempty"`          // 用户ID
		Num       int64      `db:"num" gorm:"column:num" json:"num,omitempty"`                      // 数量
		CreatedAt *time.Time `db:"created_at" gorm:"column:created_at" json:"created_at,omitempty"` // 创建时间
		UpdatedAt *time.Time `db:"updated_at" gorm:"column:updated_at" json:"updated_at,omitempty"` // 更新时间
	}
)

func newDefaultNutritionStoreModel(config gormdb.Config) *defaultNutritionStoreModel {

	cacheGormDB := gormdb.MustNewCacheGormDB[NutritionStore, int64](config)
	return &defaultNutritionStoreModel{
		db: cacheGormDB,
	}

}

func (m *defaultNutritionStoreModel) Insert(ctx context.Context, data *NutritionStore, delCacheKeys ...string) (int64, error) {
	nutritionStoreUserIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreUserIdPrefix, data.UserId)
	afterDel := true
	cacheKeys := make([]string, 0, 2)
	cacheKeys = []string{nutritionStoreUserIdKey}
	if len(delCacheKeys) > 0 {
		cacheKeys = append(cacheKeys, delCacheKeys...)
	}

	if data.Id != 0 {
		afterDel = false
		nutritionStoreIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreIdPrefix, data.Id)
		cacheKeys = append(cacheKeys, nutritionStoreIdKey)
	}

	result, err := m.db.ExecCtx(ctx, func(ctx context.Context, db *gorm.DB) (int64, error) {
		res := db.WithContext(ctx).Model(&NutritionStore{}).Create(data)
		return res.RowsAffected, res.Error
	}, cacheKeys...)

	if err != nil {
		return 0, err
	}

	if afterDel {
		nutritionStoreIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreIdPrefix, data.Id)
		err = m.db.DelCacheKeys(ctx, nutritionStoreIdKey)
		if err != nil {
			return 0, err
		}
	}
	return result, err

}

func (m *defaultNutritionStoreModel) FindById(ctx context.Context, id int64) (*NutritionStore, error) {
	nutritionStoreIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreIdPrefix, id)
	var resp NutritionStore
	err := m.db.QueryOneByPKCtx(ctx, &resp, nutritionStoreIdKey, func(ctx context.Context, r any, db *gorm.DB) error {
		return db.WithContext(ctx).Model(&NutritionStore{}).Where("`id`=?", id).Take(r).Error
	})
	return &resp, err

}

func (m *defaultNutritionStoreModel) UpdateById(ctx context.Context, id int64, updateObj *NutritionStore, delCacheKeys []string, fields ...string) (int64, error) {
	if updateObj == nil {
		return 0, nil
	}

	data, err := m.FindById(ctx, id)
	if err != nil {
		return 0, err
	}
	nutritionStoreIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreIdPrefix, data.Id)
	nutritionStoreUserIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreUserIdPrefix, data.UserId)

	delKeys := []string{nutritionStoreIdKey, nutritionStoreUserIdKey}
	if len(delCacheKeys) > 0 {
		delKeys = append(delKeys, delCacheKeys...)
	}

	return m.db.ExecCtx(ctx, func(ctx context.Context, db *gorm.DB) (int64, error) {
		upTx := db.WithContext(ctx).Model(&NutritionStore{}).Where("`id`=?", id)
		if len(fields) > 0 {
			upTx = upTx.Select(strings.Join(fields, ",")).Updates(updateObj)
		} else {
			upTx = upTx.Save(updateObj)
		}
		return upTx.RowsAffected, upTx.Error
	}, delKeys...)

}

func (m *defaultNutritionStoreModel) DeleteById(ctx context.Context, id int64, delCacheKeys ...string) (int64, error) {

	data, err := m.FindById(ctx, id)
	if err != nil {
		return 0, err
	}

	nutritionStoreIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreIdPrefix, id)
	nutritionStoreUserIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreUserIdPrefix, data.UserId)
	delKeys := []string{nutritionStoreIdKey, nutritionStoreUserIdKey}
	if len(delCacheKeys) > 0 {
		delKeys = append(delKeys, delCacheKeys...)
	}

	return m.db.ExecCtx(ctx, func(ctx context.Context, db *gorm.DB) (int64, error) {
		res := db.WithContext(ctx).Where("id = ?", id).Delete(&NutritionStore{})
		return res.RowsAffected, res.Error
	}, delKeys...)

}

func (m *defaultNutritionStoreModel) FindOneByUserId(ctx context.Context, userId int64) (*NutritionStore, error) {

	nutritionStoreUserIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreUserIdPrefix, userId)

	var Id int64
	err := m.db.QueryToGetPKCtx(ctx, nutritionStoreUserIdKey, &Id, func(ctx context.Context, p *int64, db *gorm.DB) error {
		return db.WithContext(ctx).Model(&NutritionStore{}).Select("`id`").Where("`user_id` = ?", userId).Take(p).Error
	})
	if err != nil {
		return nil, err
	}
	nutritionStoreIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreIdPrefix, Id)
	var resp NutritionStore
	err = m.db.QueryOneByPKCtx(ctx, &resp, nutritionStoreIdKey, func(ctx context.Context, r any, db *gorm.DB) error {
		return db.WithContext(ctx).Model(&NutritionStore{}).Where("`id` = ?", Id).Take(r).Error
	})
	return &resp, err

}

func (m *defaultNutritionStoreModel) UpdateOneByUserId(ctx context.Context, userId int64, updateObj *NutritionStore, delCacheKeys []string, fields ...string) (int64, error) {
	if updateObj == nil {
		return 0, nil
	}

	data, err := m.FindOneByUserId(ctx, userId)
	if err != nil {
		return 0, err
	}
	nutritionStoreIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreIdPrefix, data.Id)
	nutritionStoreUserIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreUserIdPrefix, data.UserId)

	delKeys := []string{nutritionStoreIdKey, nutritionStoreUserIdKey}
	if len(delCacheKeys) > 0 {
		delKeys = append(delKeys, delCacheKeys...)
	}

	return m.db.ExecCtx(ctx, func(ctx context.Context, db *gorm.DB) (int64, error) {
		upTx := db.WithContext(ctx).Model(&NutritionStore{}).Where("`id`", userId)
		if len(fields) > 0 {
			upTx = upTx.Select(strings.Join(fields, ",")).Updates(updateObj)
		} else {
			upTx = upTx.Save(updateObj)
		}
		return upTx.RowsAffected, upTx.Error
	}, delKeys...)

}
func (m *defaultNutritionStoreModel) DeleteOneByUserId(ctx context.Context, userId int64, delCacheKeys ...string) (int64, error) {

	data, err := m.FindOneByUserId(ctx, userId)
	if err != nil {
		return 0, err
	}
	nutritionStoreIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreIdPrefix, data.Id)
	nutritionStoreUserIdKey := fmt.Sprintf("%s%v", cacheNutritionStoreUserIdPrefix, data.UserId)

	delKeys := []string{nutritionStoreIdKey, nutritionStoreUserIdKey}
	if len(delCacheKeys) > 0 {
		delKeys = append(delKeys, delCacheKeys...)
	}

	return m.db.ExecCtx(ctx, func(ctx context.Context, db *gorm.DB) (int64, error) {
		delTx := db.WithContext(ctx).Where("`id`", userId).Delete(&NutritionStore{})
		return delTx.RowsAffected, delTx.Error
	}, delKeys...)

}

func (NutritionStore) TableName() string {
	return "nutrition_store"
}
