package template

import (
	_ "embed"
	"fmt"
)

const DoNotEditHead = "// Code generated by gotool. DO NOT EDIT. \n// If you find any bugs, please contact heshiyingx@126.com. \n// Your help is greatly appreciated.\n\n"

// Customized defines a template for customized in model
//
//go:embed tpl/customized.tpl
var Customized string

// Vars defines a template for var block in model
//
//go:embed gorm_tpl/var.tpl
var Vars string

// Types defines a template for types in model.
//
//go:embed gorm_tpl/types.tpl
var Types string

// Tag defines a tag template text
//
//go:embed gorm_tpl/tag.tpl
var Tag string

// TableName defines a template that generate the tableName method.
//
//go:embed gorm_tpl/table-name.tpl
var TableName string

// New defines the template for creating model instance.
//
//go:embed gorm_tpl/model-new.tpl
var New string

// ModelCustom defines a template for extension
//
//go:embed gorm_tpl/model.tpl
var ModelCustom string

// ModelGen defines a template for model
var ModelGen = fmt.Sprintf(`%s

package {{.pkg}}
{{.imports}}
{{.vars}}
{{.types}}
{{.new}}
{{.opCode}}
{{.extraMethod}}
{{.tableName}}
{{.customized}}
`, DoNotEditHead)

// Insert defines a template for insert code in model
//
//go:embed gorm_tpl/insert.tpl
var Insert string

// InsertMethod defines an interface method template for insert code in model
//
//go:embed gorm_tpl/interface-insert.tpl
var InsertMethod string

// Update defines a template for generating update codes
//
//go:embed gorm_tpl/update_by_pk.tpl
var Update string

// UpdateMethod defines an interface method template for generating update codes
//
//go:embed gorm_tpl/interface-update-by-pk.tpl
var UpdateMethod string

// Imports defines a import template for model in cache case
//
//go:embed gorm_tpl/import.tpl
var Imports string

// ImportsNoCache defines a import template for model in normal case
//
//go:embed gorm_tpl/import-no-cache.tpl
var ImportsNoCache string

// FindByPK defines find row by PK.
//
//go:embed gorm_tpl/find-one-by-pk.tpl
var FindByPK string

// FindOneByField defines find row by field.
//
//go:embed gorm_tpl/find-one-by-unique.tpl
var FindOneByField string

// FindOneByFieldExtraMethod defines find row by field with extras.
//
//go:embed tpl/find-one-by-field-extra-method.tpl
var FindOneByFieldExtraMethod string

// FindOneMethod defines find row method.
//
//go:embed gorm_tpl/interface-find-by-pk.tpl
var FindOneMethod string

// FindOneByFieldMethod defines find row by field method.
//
//go:embed gorm_tpl/interface-find-one-by-unique.tpl
var FindOneByFieldMethod string

// Field defines a filed template for types
//
//go:embed gorm_tpl/field.tpl
var Field string

// VarFile defines an error template
//
//go:embed gorm_tpl/var_file.tpl
var VarFile string

// Delete defines a delete template
//
//go:embed gorm_tpl/delete.tpl
var Delete string

// DeleteMethod defines a delete template for interface method
//
//go:embed gorm_tpl/interface-delete.tpl
var DeleteMethod string
