# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release
on:
  release:
    types: [created]  # 表示在创建新的 Release 时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: true

      # 清理未跟踪的文件以确保工作区干净
      - name: Clean up untracked files
        run: git clean -f -d

      # 编译并构建项目，指定输出文件位置
      - name: Build
        run: go build -o gotool -v cmd/main.go

      # 使用 goreleaser-action 生成多平台代码并发布到 GitHub Release
      - name: Create release on GitHub
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
